name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fake-news-detection-app/
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './fake-news-detection-app/package-lock.json'
      - run: npm ci
      - run: npm run build --if-present
      - name: Create dist directory
        run: mkdir dist
      - name: Copy files to dist directory
        run: rsync -av --exclude dist ./ dist/
      - run: npm test

      - name: Update repository path
        run: |
          sed -i 's#https://github.com/SuperSaiyansUcd/Fake-News-Detection-#https://github.com/SuperSaiyansUcd/Fake-News-Detection-/tree/main/fake-news-detection-app#' package.json 


          
      # gh-pages requires the repo to be public so we won't do it right now
      # - name: Deploy with gh-pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
